# Generated by Django 5.0.7 on 2024-07-25 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='open_datetime',
        ),
        migrations.AddField(
            model_name='parcel',
            name='update_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
